# Generated by Django 5.1.1 on 2024-10-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at'], 'verbose_name': 'One Time Password', 'verbose_name_plural': 'One Time Passwords'},
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
