# Generated by Django 5.1.1 on 2024-10-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_otp_options_rename_otp_otp_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('data', models.TextField()),
            ],
        ),
    ]
