# Generated by Django 5.1.1 on 2024-10-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_encryptedblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={},
        ),
    ]
